config/routes.rb
Rails.application.routes.draw do

  resources :simplex, only: :index do
    post 'result', on: :collection
  end

  resources :knapsack, only: :index do
    post 'result', on: :collection
  end

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/knapsack.rb
class Knapsack
  def initialize(max, w, c)
    @weight = w
    @cost = c
    @max = max
    @qtd_items = c.length - 1
    @items = []
    @matrix = []
    head = Array.new(max + 1, 0)
    @matrix << head
    calc_matrix
  end

  def calc_matrix
    line = []
    0.upto(@qtd_items) do |i|
      0.upto(@max) do |j|
        if @weight[i] > j
          line << @matrix[i][j]
        else
          aux = @cost[i] + @matrix[i][j - @weight[i]]
          if aux > @matrix[i][j]
            line << aux
          else
            line << @matrix[i][j]
          end
        end
      end
      @matrix << line.clone
      line.clear
    end
    solve(@qtd_items, @max)
  end

  def solve(i, j)
    unless i == -1
      p [[i + 1,j],@matrix[i + 1][j], "==", @matrix[i][j]]
      if @matrix[i + 1][j] == @matrix[i][j]
        solve(i - 1, j)
      else
        @items[i] = j
        solve(i - 1, j - @weight[i])
      end
    end
  end

  def result
    [@matrix, @items]
  end
end

app/controllers/concerns/simplex.rb
class Simplex
  # construtor, cria tabela em array
  def initialize(z,sa,b)
    @qtd_var = z.length
    @qtd_sa = sa.length
    @b = b
    x = []
    f = []
    zi = []
    @table = []

    # popula valores de f para tabela
    fmatrix = Array.new(@qtd_sa){Array.new(@qtd_sa, 0)}
    1.upto(@qtd_var) { |n| x << "x" + "#{n}" }
    1.upto(@qtd_sa) { |n| f << "f" + "#{n}" }
    @table << ['linha','base',*x,*f,'b']

    # inverte o sinal das variaveis z
    z.each do |aux|
      zi << aux * -1
    end

    # popula a array table
    #sa.map.with_index do |aux,i|
    0.upto(@qtd_sa - 1) do |i|
      fmatrix[i][i] = 1
      @table << [(i + 1).to_s, f[i], *sa[i], *fmatrix[i], b[i]]
    end
    @table << [@table.length.to_s, 'z', *zi, *Array.new(@qtd_sa + 1, 0)]
  end

  # converte a tabela inteira para string
  def table_s(tb = nil)
    if tb.nil?
      aux = @table.clone
    else
      aux = tb
    end
    l = []
    table_str = []
    aux.each do |line|
      line.each do |e|
        if e.class == String
          l << e
        else
          l << e.round(3).to_s
        end
      end
      table_str << l.clone
      l.clear
    end
    table_str
  end

  def solve
    pivot_col = coef_col
    if coef_col.nil?
      nil
    else
      table_len = (@qtd_sa + @qtd_var + 2)
      menor = 100_000_000
      pivot_row = nil
      1.upto(@qtd_sa) do |i|
        if @table[i][pivot_col] > 0 && @table[i].last.fdiv(@table[i][pivot_col]) < menor
          menor = @table[i].last.fdiv(@table[i][pivot_col])
          pivot_row = i
        end
      end

      # valor do pivô
      piv_val = @table[pivot_row][pivot_col]
      # coloca variavel na base
      @table[pivot_row][1] = @table[0][pivot_col]

      # divide elementos da linha do pivô
      2.upto(table_len) do |i|
        @table[pivot_row][i] = @table[pivot_row][i].fdiv(piv_val)
      end

      # reajusta tabela
      1.upto(@table.length - 1) do |i|
        if @table[i][pivot_col] != 0 && i != pivot_row
          piv_aux = (@table[i][pivot_col] * -1)
          2.upto(table_len) do |j|
            @table[i][j] = ((@table[pivot_row][j] * piv_aux) + @table[i][j])
          end
        end
      end
      @table
    end
  end

  def result
    col_begin = (2 + @qtd_var)
    col_end = (col_begin + @qtd_sa - 1)
    table_aux = []
    table = []

    # calcula análise de sensibilidade para todos elementos
    col_begin.upto(col_end) do |i|
      line = []
      1.upto(@qtd_sa) do |j|
        if @table[j][i] == 0
          line << 0
        else
          line << @table[j].last / (@table[j][i] * -1)
        end
      end
      table_aux << [@table.last[i], *line.minmax]
      line.clear
    end

    # monta tabela organizada para uso na view
    table_aux.each_with_index do |el,i|
      line = []
      line << el[0]
      1.upto(2) do |j|
        aux = el[j] + @b[i]
        if el[j] == 0 or aux < 0
          line << ""
        else
          line << aux
        end
      end
      line.insert(0, "R" + (i + 1).to_s)
      line << @b[i]
      table << line.clone
      line.clear
    end
    table
  end

  # busca coluna do coeficiente
  def coef_col
    if @table.last[2..(@qtd_var + 1)].min == 0
      nil
    else
      @table.last.index(@table.last[2..(@qtd_var + 1)].min)
    end
  end

  # retorna se é calculavel
  def can_improve?
    if coef_col.nil?
      false
    else
      true
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/knapsack_controller.rb
class KnapsackController < ApplicationController
  def index
  end

  def result
    @max_weight = knapsack_params['input1'].to_i
    @w = knapsack_params['w'].map(&:to_i)
    @c = knapsack_params['c'].map(&:to_i)
    @str = ["Peso", "Valor"]

    @out = Knapsack.new(@max_weight, @w, @c)
    array = @out.result

    @table = array[0]
    @items = array[1]
  end

  private
  def knapsack_params
    params.permit!
  end
end

app/controllers/simplex_controller.rb
class SimplexController < ApplicationController
  def index
  end

  def result
    sa = []
    @tables = []

    simplex_params['sa'].each do |x|
      sa << x[1].map(&:to_f)
    end

    z = simplex_params['z'].map(&:to_f)
    b = simplex_params['b'].map(&:to_f)

    @out = Simplex.new(z,sa,b)
    @table = @out.table_s

    until @out.solve.nil?
      @tables << @out.table_s
    end

    @result = @out.table_s(@out.result)
  end

  private
  def simplex_params
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_active_btn(btn, path)
    if current_page? path
      content_tag :li, link_to(btn, path), :class => 'active'
    else
      content_tag :li, link_to(btn, path)
    end
  end

  def opt_name(path)
    if path == "/simplex"
      @path = result_simplex_index_path
      @input1 = "Quantidade de Variáveis: "
      @input2 = "Quantidade de Restrições: "
      @opt = 0
    elsif path == "/knapsack"
      @path = result_knapsack_index_path
      @input1 = "Capacidade Máxima: "
      @input2 = "Quantidade de Itens: "
      @opt = 1
    end
  end
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-11 col-md-offset-1 col-sm-12 col-xs-12">
    <h3>Trabalho de Pesquisa Operacional</h3>
    <p><strong>Alunos</strong></p>
    <ul>
      <li>Claudio Costa &raquo; 527033</li>
      <li>Cristiano Vicente &raquo; RA 443913</li>
      <li>Vitoria Mendes Lopes Nunes &raquo; RA 525324</li>
    </ul>
    <p>Bacharelandos do 6º semestre de Ciência da Computação na UNIVEM - Fundação Eurípedes Soares da Rocha</p>
    <p>Professor Ricardo Sabatini</p>
  </div>
</div>

app/views/knapsack/_knapsack.html.erb
<div id="parte2">
  <p class="text-center"><cite><strong>Itens</strong></cite></p>
  <table class="xcenter" id="item">
    <!-- item -->
  </table>
  <br>

  <p class="text-center">
    <button class="btn-warning btn"> Resultado &raquo; </button>
  </p>
</div>

app/views/knapsack/index.html.erb
<%= render 'layouts/form' %>

app/views/knapsack/result.html.erb
<div class="container-fluid">
  <div class="container xcenter">
    <h2 class="text-center"><cite>Itens</cite></h2>

    <div class="container-fluid">
      <!-- tabela de itens -->
      <table class="table table-striped table-hover">
        <!-- Objetos index -->
        <thead>
        <tr>
          <th>Objeto</th>
          <% 1.upto(@w.length) do |i| %>
              <% if @items[i - 1].nil? %>
                  <th>
              <% else %>
                  <th class="alert-success">
              <% end %>
              <%= i %></th>
          <% end %>
        </tr>
        </thead>
        <!-- Peso -->
        <tr>
          <th><%= @str[0] %></th>
          <% @w.each_with_index do |el, i| %>

              <% if @items[i].nil? %>
                  <td>
              <% else %>
                  <td class="success">
              <% end %>
              <%= el %></td>

          <% end %>
        </tr>
        <!-- Valor -->
        <tr>
          <th><%= @str[1] %></th>
          <% @c.each_with_index do |el, i| %>

              <% if @items[i].nil? %>
                  <td>
              <% else %>
                  <td class="success">
              <% end %>
              <%= el %></td>

          <% end %>
        </tr>

      </table>
    </div>

    <h2 class="text-center"><cite>Resultado</cite></h2>

    <div class="container-fluid">
      <!-- tabela do resultado -->
      <table class="table table-striped table-hover table-bordered text-center">

        <thead>
        <tr>
          <th></th>
          <% 0.upto(@max_weight) do |i| %>
              <th><%= i %></th>
          <% end %>
        </tr>
        </thead>

        <% @table.each_with_index do |line, i| %>

            <tr>
              <% if @items[i - 1] and i > 0 %>
                  <th class="alert-info">
              <% else %>
                  <th>
              <% end %>
              <%= i %></th>

              <% line.each_with_index do |el, j| %>
                  <% if @items[i] and @items[i] == j %>
                      <td class="alert-danger">
                  <% elsif @items[i - 1] and @items[i - 1] == j and i > 0 %>
                      <td class="alert-success">
                  <% else %>
                      <td>
                  <% end %>
                  <%= el %></td>
              <% end %>
            </tr>
        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/layouts/_form.html.erb
<div class="maxh pre-scrollable">
  <!--form action="" method="POST"-->
  <% opt_name(request.path) %>
  <%= form_tag(@path, class: "form-inline") do %>
      <div class="content">
        <div id="parte1 form-group">
          <p class="text-center"><cite><strong>Informações</strong></cite></p><br/>
          <label for="input1"><%= @input1 %></label>
          <input type="number" class="form-control fci-size" name="input1" id="input1" autofocus size="3" min="1"/>

          <label for="input2">&nbsp;<%= @input2 %></label>
          <input type="number" class="form-control fci-size" name="input2" id="input2" size="3" min="1"/>
        </div>

        <br>

        <p class="text-center">
          <button class="btn-warning btn" id="btn-valida" onclick="event.preventDefault(); valida();">
            Continuar &raquo; </button>
        </p>
      </div>
      <br/><br/>

      <% if @opt == 0 %>
          <%= render 'simplex/simplex' %>
      <% elsif @opt == 1 %>
          <%= render 'knapsack/knapsack' %>
      <% end %>

      <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pesquisa-Operacional</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#disboard">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pesquisa-Operacional', root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="disboard">
      <ul class="nav navbar-nav">
        <%= nav_active_btn("Simplex", simplex_index_path) %>
        <%= nav_active_btn("Knapsack", knapsack_index_path) %>
      </ul>
    </div>
  </div>
</nav>
<div class="conteiner-fluid maxh">

  <%= yield %>

</div>
</body>
</html>

app/views/simplex/_simplex.html.erb
<div id="parte2">
  <p class="text-center"><cite><strong>Variáveis</strong></cite></p>
  <table class="xcenter">
    <tr id="valname">
      <!-- label -->
    </tr>
    <tr id="funcao">
      <!-- Variáveis -->
    </tr>
  </table>
  <br/>

  <p class="text-center"><cite><strong>Restrições</strong></cite></p>
  <table id="restricoes" class="xcenter">

  </table>
  <br>

  <p class="text-center">
    <button class="btn-warning btn"> Resultado &raquo; </button>
  </p>
</div>

app/views/simplex/index.html.erb
<%= render "layouts/form" %>

app/views/simplex/result.html.erb
<div class="container-fluid">
  <div class="container xcenter">
    <h2 class="text-center"><cite>Tabelas</cite></h2>

    <div class="container-fluid">
      <div id="tables" class="carousel slide container-fluid" data-ride="carousel" data-interval="false">
        <!-- Indicators -->
        <ol class="carousel-indicators">

          <% 0.upto(@tables.length - 1) do |i| %>
              <li data-target="#tables" data-slide-to="<%= i %>"></li>
          <% end %>
          <li data-target="#tables" data-slide-to="0" class="active carousel-pos"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item">
            <div class="text-center">
              <h3><label class="label label-default">Tabela Inicial</label></h3>
              <br>
            </div>
            <!-- Tabela inicial -->
            <table class="table table-striped table-hover">
              <% @table.each_with_index do |line, i| %>
                  <tr>
                    <% line.each do |el| %>
                        <% if i == 0 %>
                            <th><%= el %></th>
                        <% else %>
                            <td><%= el %></td>
                        <% end %>
                    <% end %>
                  </tr>
              <% end %>
            </table>
          </div>
          <!-- Tabelas seguintes -->
          <% @tables.each_with_index do |tb, index| %>
              <% if @tables.length - 1 == index %>
                  <div class="item active">
                    <div class="text-center">
                      <h3><label class="label label-default">Iteração <%= index + 1 %> - Tabela Final</label></h3>
                      <br>
                    </div>
              <% else %>
                  <div class="item">
                    <div class="text-center">
                      <h3><label class="label label-default">Iteração <%= index + 1 %></label></h3>
                      <br>
                    </div>
              <% end %>

              <table class="table table-striped table-hover">
                <% tb.each_with_index do |line, i| %>
                    <tr>
                      <% line.each do |el| %>
                          <% if i == 0 %>
                              <th><%= el %></th>
                          <% else %>
                              <td><%= el %></td>
                          <% end %>
                      <% end %>
                    </tr>
                <% end %>
              </table>
              </div>
          <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#tables" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#tables" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
  <br>

  <div class="container-fluid">
    <div class="container xcenter">
      <h2 class="text-center"><cite>Resultado</cite></h2>
      <table class="table table-striped table-hover">
        <tr>
          <th></th>
          <th>Custo Sombra</th>
          <th>L. Min</th>
          <th>L. Max</th>
          <th>Valor</th>
        </tr>
        <!-- Tabela Resultado - Análise de sensibilidade -->
        <% @result.each do |line| %>
            <tr>
              <% line.each do |e| %>
                  <td><%= e %></td>
              <% end %>
            </tr>
        <% end %>

      </table>
    </div>
  </div>
</div>